version: '3.8'
services:
  server:
    build: .
    command: npm run server
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/j9
    depends_on:
      - mongo
  client:
    build: .
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
    depends_on:
      - server
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
